resolver: lts-9.9

packages:
- '.'
- location:
    git: https://github.com/adjoint-io/merkle-tree.git 
    commit: 4a33f7868b89c7c54f44b9d409d378ae54bf92ee  
  extra-dep: true

# Dependency packages to be pulled from upstream that are not in the resolver
# (e.g., acme-missiles-0.3)
extra-deps: 
- base58-bytestring-0.1.0
- protolude-0.2

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []
